-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;
CREATE DATABASE IF NOT EXISTS whispr;

CREATE TABLE IF NOT EXISTS whispr.users
(
    user_id integer NOT NULL,
    user_name character varying(20) NOT NULL,
    email character varying(255) NOT NULL,
    password character varying(255) NOT NULL,
    PRIMARY KEY (user_id),
    UNIQUE (user_name),
    UNIQUE (email),
	ON UPDATE CASCADE,
	ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS whispr.reactions
(
    reaction_id integer NOT NULL,
    user_id integer,
    message_id integer NOT NULL,
    reaction_role character(50) NOT NULL,
    PRIMARY KEY (reaction_id),
	FOREIGN KEY (user_id) REFERENCES whispr.users (user_id)
);

CREATE TABLE IF NOT EXISTS whispr.channels
(
    channel_id integer NOT NULL,
    channel_title character varying(20) NOT NULL,
    channel_status character(10) NOT NULL,
    PRIMARY KEY (channel_id)
	ON UPDATE NO ACTION,
	ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS whispr.messages
(
    message_id integer NOT NULL,
    user_id integer,
    channel_id integer NOT NULL,
    date_time time without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    content character varying(1000) NOT NULL,
    PRIMARY KEY (message_id),
	FOREIGN KEY (user_id) REFERENCES whispr.users (user_id),
	FOREIGN KEY (channel_id) REFERENCES whispr.channels (channe_id),
	ON UPDATE NO ACTION,
	ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS whispr.channels_access
(
    access_id integer NOT NULL,
    user_id integer NOT NULL,
    channel_id integer NOT NULL,
    role_title character(10) NOT NULL,
    PRIMARY KEY (access_id),
	FOREIGN KEY (user_id) REFERENCES whispr.users (user_id),
	FOREIGN KEY (channe_id) REFERENCES whispr.channels (channel_id)
	ON UPDATE NO ACTION,
	ON DELETE NO ACTION
);


END;